import app from "./app";


const port : number  = 3000;

app.listen(port, () => {
    //console.log(__dirname)
    console.log(`server is running on port 3000:  ${port}`);
    
});                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              